name: Run tests

on:
  push:
    paths:
      - 'backend/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: tests
  cancel-in-progress: false

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build-and-test-backend:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Test report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Backend test reports
          path: build/test-results/test/*.xml
          reporter: java-junit
          fail-on-error: true
